---
kind: Service
apiVersion: v1
metadata:
  name: kubecost-exporter
  namespace: kubecost-exporter
  labels:
    app: kubecost-exporter
spec:
  selector:
    app: kubecost-exporter
  ports:
    - name: metrics
      port: 9150

---
kind: ServiceMonitor
apiVersion: monitoring.coreos.com/v1
metadata:
  name: kubecost-exporter
  namespace: kubecost-exporter
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: kubecost-exporter
  endpoints:
    - port: metrics
      interval: 60s
      params:
        collect[]:
          - scrape_assets
        scrape_assets[]:
          - window=7d